### PR TITLE
Twu/rotate bug

### LINKED ISSUE #177: Rotating while search results loading causes a crash
Hi

PHC++

### PR DESCRIPTION
**Pull request by twuster**
fixes #177

### CODE REVIEW

File: PHC-Android/PHC/src/main/java/phc/android/SearchResultsFragment.java [hunk 1]
```diff
@@ -84,6 +104,17 @@ public void onActivityCreated (Bundle savedInstanceState) {
     }
 
     @Override
+    public void onSaveInstanceState(Bundle outState) {
+        // Save the cached results
+        outState.putParcelableArray(CACHED_RESULTS, mSearchResults);
```
Comment (Byronium) [inline PHC-Android/PHC/src/main/java/phc/android/SearchResultsFragment.java]: this is interesting - i thought that Bundles could only store primitive types. so it can store parceled information too? is this because once these things are parceled, they basically become serialized to ints?
